# Generated by Django 2.2.6 on 2019-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=35, null=True)),
                ('esal', models.IntegerField(default=0.0)),
                ('eaddress', models.CharField(max_length=35)),
                ('Designation', models.CharField(max_length=60)),
            ],
        ),
    ]
