# Generated by Django 2.2.6 on 2019-10-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'EmployeesInformation'},
        ),
    ]
